#!/bin/bash
# ╭──────────────────────────────────────────────────────────────────────────────╮
# │                                                                              │
# │           Volume-Dump. An extension of the Vackup tool which also            │
# │               Allows for MySQL Dumps to be backed up as well.                │
# │                     Inspired by Bret Fishers Vackup tool                     │
# │                                                                              │
# ╰──────────────────────────────────────────────────────────────────────────────╯

# ╭──────────────────────────────────────────────────────────╮
# │                       Set Defaults                       │
# ╰──────────────────────────────────────────────────────────╯

# set -o errexit                                              # If a command fails bash exits.
set -Eeo pipefail                                             # pipeline fails on one command.
if [[ "${DEBUG-0}" == "1" ]]; then set -o xtrace; fi          # DEBUG=1 will show debugging.


# ╭──────────────────────────────────────────────────────────╮
# │                        VARIABLES                         │
# ╰──────────────────────────────────────────────────────────╯
DB_USERNAME="root"

# ╭──────────────────────────────────────────────────────────╮
# │                      Trap Functions                      │
# ╰──────────────────────────────────────────────────────────╯

# Remove the backup.sql file on exit.
trap "rm -f ./backup.sql" EXIT

# ╭──────────────────────────────────────────────────────────╮
# │                     Menu Definitions                     │
# ╰──────────────────────────────────────────────────────────╯
function menu_main()
{
    printf "Vump Tool\n\n"
    printf "1. Export Volume contents to host tar.gz file\n"
    printf "2. Import tar.gz file into a Volume\n"
    printf "3. Save Volume data to a backup docker image\n"
    printf "4. Load backup docker image into a Volume\n"
    printf "5. Save MySQL Volume DB to a backup docker image\n"
    printf "6. Load backup MySQL DB docker image into DB Volume\n"

    printf "\n"
    read -n 1 -p "Enter option (1-6) to continue" SELECTION; clear

    case $SELECTION in

        1)
            cmd_export ;;


        2)
            cmd_import ;;


        3)
            cmd_save ;;


        4)
            cmd_load ;;


        5)
            cmd_dbsave ;;


        6)
            cmd_dbload ;;


        *)
            echo "Unknown option $1"
            menu_main
            ;;

    esac

}


# ╭──────────────────────────────────────────────────────────╮
# │          Select a docker container from a list           │
# ╰──────────────────────────────────────────────────────────╯
function select_container()
{
    clear
    printf "### %s\n\n" "$1"

    printf "Select a Container\n"

    LIST_OF_CONTAINERS=$(docker container ls -a --format='{{.ID}}\t{{.Names}}\t\t{{.Image}}')

    LOOP=1
    while IFS= read -r line; do
        echo "$LOOP. $line"
        LOOP=$(( LOOP+1 ))
    done <<< "$LIST_OF_CONTAINERS"

    read -n 2 -p "$QUESTION" ANSWER

    CONTAINER_LINE=$(sed -n ${ANSWER}p <<< "$LIST_OF_CONTAINERS")
    CONTAINER=$(echo $CONTAINER_LINE  | head -n1 | cut -d " " -f2 | xargs )

    echo $CONTAINER
}

# ╭──────────────────────────────────────────────────────────╮
# │             Select a docker volume from list             │
# ╰──────────────────────────────────────────────────────────╯
function select_volume()
{
    clear
    printf "### %s\n\n" "$1"

    printf "Select a Volume\n"

    LIST_OF_VOLUMES=$(docker volume ls --format='{{lower .Name}}')

    LOOP=1
    while IFS= read -r line; do
        echo "$LOOP. $line"
        LOOP=$(( LOOP+1 ))
    done <<< "$LIST_OF_VOLUMES"

    read -n 2 -p "$QUESTION" ANSWER

    VOLUME_LINE=$(sed -n ${ANSWER}p <<< "$LIST_OF_VOLUMES")
    VOLUME=$(echo $VOLUME_LINE  | head -n1 | cut -d " " -f1 )

    echo $VOLUME
}


# ╭──────────────────────────────────────────────────────────╮
# │              Select a docker image for list              │
# ╰──────────────────────────────────────────────────────────╯
function select_image()
{
    clear
    printf "### %s\n\n" "$1"

    printf "Select an Image\n"

    LIST_OF_IMAGES=$(docker image ls --format='{{lower .ID}}\t{{lower .Repository}}')

    LOOP=1
    while IFS= read -r line; do
        echo "$LOOP. $line"
        LOOP=$(( LOOP+1 ))
    done <<< "$LIST_OF_IMAGES"

    read -n 2 -p "$QUESTION" ANSWER

    IMAGE_LINE=$(sed -n ${ANSWER}p <<< "$LIST_OF_IMAGES")
    IMAGE=$(echo $IMAGE_LINE  | head -n1 | cut -d " " -f1 )

    echo $IMAGE

}


# ╭──────────────────────────────────────────────────────────╮
# │                      Ask a question                      │
# ╰──────────────────────────────────────────────────────────╯
function ask_question()
{
    clear
    printf "### \n\n "

    QUESTION=$1

    read -p "$QUESTION" ANSWER

    echo $ANSWER
}



# ╭──────────────────────────────────────────────────────────╮
# │                          EXPORT                          │
# ╰──────────────────────────────────────────────────────────╯
#
# Copy files from a volume into a tar.gz file on the host.
# 
# 1. Create a BUSYBOX container
# 2. mount volume to    /vackup-volume
# 3. mount $pwd to      /vackup
# 4. create tar.gz of volume into $pwd
#                                ┌──────────────────────┐
# ┌────────────────┐             │ ┌────────────────┐   │
# │       ./       │────mount────┼▶│    /vackup     │   │
# └────────────────┘             │ └──────────────▲─┘   │
#                                │                │     │
#                                │ busybox       tar -c │
#                                │                │     │
# ┌────────────────┐             │ ┌──────────────┴─┐   │
# │     volume     │────mount────┼▶│ /vackup-volume │   │
# └────────────────┘             │ └────────────────┘   │
#                                └──────────────────────┘
function cmd_export() {

    select_volume "Select volume to EXPORT from"
    VOLUME_NAME="$VOLUME"
    ask_question "Filename to export to? "
    FILE_NAME="$ANSWER"
    
    # Add tar.gz on the end.
    if [[ ! $FILE_NAME == *.tar.gz ]]; then
        FILE_NAME="$FILE_NAME.tar.gz"
    fi

    # Check parameters are set
    if [ -z "$VOLUME_NAME" ] || [ -z "$FILE_NAME" ]; then
        echo "Error: Not enough arguments"
        usage
        exit 1
    fi
    
    # Check docker volume exists
    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME";
    then
        echo "Error: Volume $VOLUME_NAME does not exist"
        exit 1
    fi

    # TODO: check if file exists on host, if it does
    # create a option for overwrite and check if that's set
    # TODO: if FILE_NAME starts with / we need to error out
    # unless we can translate full file paths


    if ! docker run --rm \
        -v "$VOLUME_NAME":/vackup-volume \
        -v "$(pwd)":/vackup \
        busybox \
        tar -zcvf /vackup/"$FILE_NAME" /vackup-volume > /dev/null 2>&1;
    then
        echo "Error: Failed to start busybox backup container"
        exit 1
    fi

    echo "Successfully tar'ed volume $VOLUME_NAME into file $FILE_NAME"
}



# ╭──────────────────────────────────────────────────────────╮
# │                          IMPORT                          │
# ╰──────────────────────────────────────────────────────────╯
# 
# Loads the contents of a backup tar.gz into a Volume.
#
# 1. Create a BUSYBOX container
# 2. mount volume to    /vackup-volume
# 3. mount $pwd to      /vackup
# 4. extract contents of tar.gz into volume
#
#                                ┌──────────────────────┐
# ┌────────────────┐             │ ┌────────────────┐   │
# │       ./       │────mount────┼▶│    /vackup     │   │
# └────────────────┘             │ └──────────────┬─┘   │
#                                │                │     │
#                                │ busybox       tar -x │
#                                │                │     │
# ┌────────────────┐             │ ┌──────────────▼─┐   │
# │     volume     │────mount────┼▶│ /vackup-volume │   │
# └────────────────┘             │ └────────────────┘   │
#                                └──────────────────────┘
#
function cmd_import() {

    ask_question "Filename to import from? "
    FILE_NAME="$ANSWER"

    select_volume "Select Volume to IMPORT into."
    VOLUME_NAME="$VOLUME"
    
    # Check parameters are set
    if [ -z "$VOLUME_NAME" ] || [ -z "$FILE_NAME" ]; then
        echo "Error: Not enough arguments"
        usage
        exit 1
    fi
    
    # Check docker volume exists
    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME";
    then
        echo "Error: Volume $VOLUME_NAME does not exist"
        docker volume create "$VOLUME_NAME"
    fi

    # TODO: check if file exists on host, if it does
    # create a option for overwrite and check if that's set
    # TODO: if FILE_NAME starts with / we need to error out
    # unless we can translate full file paths    

    if ! docker run --rm \
        -v "$VOLUME_NAME":/vackup-volume \
        -v "$(pwd)":/vackup \
        busybox \
        tar -xvzf /vackup/"$FILE_NAME" -C /; 
    then
        echo "Error: Failed to start busybox container"
        exit 1
    fi

    echo "Successfully unpacked $FILE_NAME into volume $VOLUME_NAME"
}


# ╭──────────────────────────────────────────────────────────╮
# │                           SAVE                           │
# ╰──────────────────────────────────────────────────────────╯
#
# Save contents of a volume to a container image.
#
# 1. Mount volume to busybox
# 2. Copy contents to /volume-data/
# 3. Make an image of the container
# 4. Delete container
#
#                               ┌──────────────────────┐
# ┌────────────────┐            │  ┌────────────────┐  │
# │     volume     │────mount───┼─▶│ /vackup-volume │  │
# └────────────────┘            │  └──────────────┬─┘  │
#                               │                 │    │
#                               │ busybox      cp -Rp  │
#                               │                 │    │
#                               │ ┌───────────────▼┐   │
#                               │ │ /volume-data/  │   │
#                               │ └────────────────┘   │
#                               └──────────────────────┘
#                                           │           
#                                           ▼           
#                               ┌──────────────────────┐
#                               │  Image of Container  │
#                               └──────────────────────┘
#
function cmd_save() {

    select_volume "Select Volume to save into a backup image."
    VOLUME_NAME="$VOLUME"

    ask_question "Name to give backup image? "
    IMAGE_NAME="$ANSWER"

    # Check parameters are set
    if [ -z "$VOLUME_NAME" ] || [ -z "$IMAGE_NAME" ]; then
        echo "Error: Not enough arguments"
        usage
        exit 1
    fi

    # Check docker volume exists
    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME"; 
    then
        echo "Error: Volume $VOLUME_NAME does not exist"
        exit 1
    fi

    # Copy everything from volume to busybox container
    if ! docker run \
        -v "$VOLUME_NAME":/mount-volume \
        busybox \
        cp -Rp /mount-volume/. /volume-data/;
    then
        echo "Error: Failed to start busybox container"
        exit 1
    fi

    # Get latest container ID (hash)
    CONTAINER_ID=$(docker ps -lq)

    # Create a new Image
    docker commit -m "saving volume $VOLUME_NAME to /volume-data" "$CONTAINER_ID" "$IMAGE_NAME"

    # Delete the container
    docker container rm "$CONTAINER_ID"

    echo "Successfully copied volume $VOLUME_NAME into image $IMAGE_NAME, under /volume-data"
}


# ╭──────────────────────────────────────────────────────────╮
# │                           LOAD                           │
# ╰──────────────────────────────────────────────────────────╯
#
# Load contents of a container image into a Volume.
#
# 1. Create container of image
# 2. Mount volume to /mount-volume
# 3. Copy everything in /volume-data to /mount-volume
#
#                               ┌──────────────────────┐
# ┌────────────────┐            │  ┌────────────────┐  │
# │     volume     │────mount───┼─▶│ /mount-volume  │  │
# └────────────────┘            │  └──────────────▲─┘  │
#                               │                 │    │
#                               │ busybox      cp -Rp  │
#                               │                 │    │
#                               │ ┌───────────────┴┐   │
#                               │ │ /volume-data/  │   │
#                               │ └────────────────┘   │
#                               └──────────────────────┘
#                                           ▲           
#                                           │           
#                               ┌──────────────────────┐
#                               │  Image of Container  │
#                               └──────────────────────┘
#
cmd_load() {

    select_image "Select backup image to load data from."
    IMAGE_NAME="$IMAGE"

    select_volume "Select volume to load data into."
    VOLUME_NAME="$VOLUME"
    
    # Check parameters are set
    if [ -z "$VOLUME_NAME" ] || [ -z "$IMAGE_NAME" ]; then
        echo "Error: Not enough arguments"
        usage
        exit 1
    fi

    # Check docker volume exists
    if ! docker volume inspect --format '{{.Name}}' "$VOLUME_NAME"; 
    then
        echo "Volume $VOLUME_NAME does not exist, creating..."
        docker volume create "$VOLUME_NAME"
    fi
    
    # Copy everything from container into volume under /mount-volume
    if ! docker run --rm \
        -v "$VOLUME_NAME":/mount-volume \
        "$IMAGE_NAME" \
        cp -Rp /volume-data/. /mount-volume/; 
    then
        echo "Error: Failed to start container from $IMAGE_NAME"
        exit 1
    fi

    echo "Successfully copied /volume-data from $IMAGE_NAME into volume $VOLUME_NAME"
}


# ╭──────────────────────────────────────────────────────────╮
# │                          DBSAVE                          │
# ╰──────────────────────────────────────────────────────────╯
#
# Extracts the database from a Volume and creates a backup image
#
# 1. Run DB Container (with DB volume mounted)
# 2. MySQLDump database to current folder
# 3. Create new busybox container
# 4. Mount current dir to container
# 5. Copy dump file into container
# 6. Make image of container
#
#                                 ┌─────────────────────────┐
#                                 │     MySQL Container     │
# ┌──────────────────┐            │                         │
# │     DB Volume    │── mount ───┼───────▶ mysqldump       │
# └──────────────────┘            │             │           │
# ┌──────────────────┐            │ ┌───────────▼─────────┐ │
# │   ./backup.sql   │◀─── cp ────┼─│   /tmp/backup.sql   │ │
# └──────────────────┘            │ └─────────────────────┘ │
#           │                     └─────────────────────────┘
#           │                                                
#           │                     ┌─────────────────────────┐
#           │                     │         busybox         │
#           │                     │                         │
#           │                     │ ┌─────────────────────┐ │
#           └─────── mount ───────┼▶│ /vackup/backup.sql  │ │
#                                 │ └──────────┬──────────┘ │
#                                 │            │ cp -p      │
#                                 │            ▼            │
#                                 │ ┌─────────────────────┐ │
#                                 │ │ /db-data/backup.sql │ │
#                                 │ └─────────────────────┘ │
#                                 └─────────────────────────┘
#                                              │ commit      
#                                              ▼             
#                                  ┌──────────────────────┐  
#                                  │  Image of Container  │  
#                                  └──────────────────────┘  
#
function cmd_dbsave() {

    select_container "Select MySQL Container to backup."
    CONTAINER="$CONTAINER"

    ask_question "Name to give backup image? "
    IMAGE_NAME="$ANSWER"

    ask_question "Name of database to backup? "
    DB_DATABASE="$ANSWER"

    ask_question "$DB_USERNAME database password? "
    DB_PASSWORD="$ANSWER"

    printf "CONTAINER: %s\n" "$CONTAINER"
    printf "IMAGE_NAME: %s\n" "$IMAGE_NAME"
    printf "DB_DATABASE: %s\n" "$DB_DATABASE"
    printf "DB_USERNAME: %s\n" "$DB_USERNAME"
    printf "DB_PASSWORD: %s\n" "$DB_PASSWORD"

    # Check parameters are set
    if [ -z "$CONTAINER" ] || [ -z "$IMAGE_NAME" ] || [ -z "$DB_DATABASE" ] || [ -z "$DB_PASSWORD" ]; then
        echo "Error: Not enough arguments"
        usage
        exit 1
    fi

    # Check docker container exists
    if ! docker ps -a | grep "$CONTAINER" > /dev/null 2>&1; 
    then
        echo "Error: Container $CONTAINER does not exist"
        exit 1
    fi

    # Check docker container has mysql
    if ! docker exec $CONTAINER \
        mysqldump --version > /dev/null 2>&1; 
    then
        echo "Error: Container $CONTAINER does not have a MySQL database"
        exit 1
    fi

    # Dump Database to /tmp
    if ! docker exec $CONTAINER \
        /bin/sh -c "mysqldump -u$DB_USERNAME -p$DB_PASSWORD -v --single-transaction $DB_DATABASE > /tmp/backup.sql";
    then
        echo "Error: Failed to dump database to /tmp/backup.sql"
        exit 1
    fi

    # Copy backup file out of container
    if ! docker cp $CONTAINER:/tmp/backup.sql ./backup.sql;
    then
        echo "Error: Unable to copy $CONTAINER:/tmp/backup.sql to current folder."
        exit 1
    fi

    # Copy backup.sql file to busybox container
    if ! docker run \
        -v "$(pwd)":/vackup \
        busybox \
        /bin/sh -c "mkdir -p /db-data/ && cp -p /vackup/backup.sql /db-data/backup.sql" ;
    then
        echo "Error: Failed to start busybox container"
        exit 1
    fi

    # Get latest container ID (hash)
    CONTAINER_ID=$(docker ps -lq)

    # Create a new Image
    docker commit -m "saving DB from container $CONTAINER to /db-data/backup.sql" "$CONTAINER_ID" "$IMAGE_NAME"

    # Delete the container
    docker container rm "$CONTAINER_ID"

    echo "Successfully copied DB in container $CONTAINER into image $IMAGE_NAME, under /db-data"
}


# ╭──────────────────────────────────────────────────────────╮
# │                          DBLOAD                          │
# ╰──────────────────────────────────────────────────────────╯
#
# Loads a database from a backup image into a Volume.
#
# 1. Download DB data image
# 2. Copy the backup file out of image
# 3. Copy backup file into target container
# 4. Load backup into MySQL.
#
# ┌─────────────────────┐         ┌─────────────────────────┐
# │  Image with Backup  │────────▶│        Container        │
# └─────────────────────┘         │                         │
#                                 │ ┌─────────────────────┐ │
#                                 │ │ /db-data/backup.sql │ │
#                                 │ └─────────────────────┘ │
#                                 │            │            │
#                                 │            │  cp -p     │
#                                 │            ▼            │
# ┌───────────────────┐           │ ┌─────────────────────┐ │
# │        ./         │◀── mount ─┼─│/opt/mount/backup.sql│ │
# └───────────────────┘           │ └─────────────────────┘ │
#           │                     └─────────────────────────┘
#           │                                                
#           │                                                
#           │                     ┌─────────────────────────┐
#           │                     │     MySQL Container     │
#           │                     │ ┌─────────────────────┐ │
#           └───────cp────────────┼▶│   /tmp/backup.sql   │ │
#                                 │ └─────────────────────┘ │
#                                 │            │            │
#                                 │            │ mysql      │
#                                 │            ▼            │
# ┌──────────────────┐            │ ┌─────────────────────┐ │
# │     DB Volume    │◀──mounted──┼─│      DATABASE       │ │
# └──────────────────┘            │ └─────────────────────┘ │
#                                 └─────────────────────────┘
#
cmd_dbload() {

    select_image "Select database image to load data from. "
    IMAGE_NAME="$IMAGE"

    select_container "Select MySQL container to load data into. "
    TARGET_CONTAINER="$CONTAINER"

    ask_question "Name of database to load? "
    DB_DATABASE="$ANSWER"

    ask_question "$DB_USERNAME database password? "
    DB_PASSWORD="$ANSWER"

    printf "CONTAINER: %s\n" "$CONTAINER"
    printf "IMAGE_NAME: %s\n" "$IMAGE_NAME"
    printf "DB_DATABASE: %s\n" "$DB_DATABASE"
    printf "DB_USERNAME: %s\n" "$DB_USERNAME"
    printf "DB_PASSWORD: %s\n" "$DB_PASSWORD"

    # Check parameters are set
    if [ -z "$TARGET_CONTAINER" ] || [ -z "$IMAGE_NAME" ] || [ -z "$DB_DATABASE" ] || [ -z "$DB_PASSWORD" ]; then
        echo "Error: Not enough arguments"
        usage
        exit 1
    fi


    # Extract backup file out of image
    if ! docker run -v $PWD:/opt/mount --rm --entrypoint cp $IMAGE_NAME /db-data/backup.sql /opt/mount/backup.sql; 
    then
        echo "Error: Could not copy backup.sql file from Image $IMAGE_NAME."
        exit 1
    fi
    
    # Copy backup file into container
    if ! docker cp ./backup.sql $TARGET_CONTAINER:/tmp/backup.sql ;
    then
        echo "Error: Unable to copy backup.sql into $TARGET_CONTAINER:/tmp/backup.sql"
        exit 1
    fi

    # Load the Mysql Database
    if ! docker exec \
        $TARGET_CONTAINER \
        /bin/sh -c "cat /tmp/backup.sql | /usr/bin/mysql -u$DB_USERNAME -p$DB_PASSWORD $DB_DATABASE > /dev/null 2>&1" ;
    then
        echo "Error: Failed to load SQL file into database."
        exit 1
    fi

    echo "Successfully loaded the SQL file from the $IMAGE_NAME image, into the $TARGET_CONTAINER DB container."
}


function mainmenu()
{
    clear
    menu_main 
}


mainmenu "$@"